#!/bin/sh

scp dist/main.js jason@appserver.workshop17.co.za:/home/jason/workspaceman/packages/openmembers/public/doors/.
scp dist/index.html jason@appserver.workshop17.co.za:/home/jason/workspaceman/packages/openmembers/public/doors/.
